# -*- coding: utf-8 -*-
"""pre_processing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LbQzCm51MkzgTbRTiTTOYnOY7tF7uCO5
"""

# # Data Preprocessing
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Mounting Google Drive
from google.colab import drive
drive.mount('/content/drive')

from google.colab import files
Uploaded=files.upload()

dataset= pd.read_csv('jugal PGI18CS021 - Classification Dataset1.csv')
dataset

dataset.isnull().sum()

dataset.dtypes

dataset.head(5)

dataset.iloc[:,4:9]

from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values= np.NAN, strategy= 'mean', fill_value=None, verbose=1, copy=True)
 
imputer = imputer.fit(dataset.iloc[:, 4:10]) 
dataset.iloc[:, 4:10]= imputer.transform(dataset.iloc[:, 4:10])

dataset.iloc[:,3] = dataset.iloc[:,3].fillna(dataset.iloc[:,3].mode()[0])

print(dataset.isnull().sum())

dataset.head(5)



X=dataset.iloc[:,1:10].values
y=dataset.iloc[:,-1].values

print(X)

from sklearn.preprocessing import LabelEncoder
labelencoder_X = LabelEncoder()
X[:, 1] = labelencoder_X.fit_transform(X[:, 1])

print(X)

from sklearn.model_selection import train_test_split
train_x,test_x,train_y,test_y=train_test_split(X,y,random_state=42,test_size=0.2)

train_x

test_x

from sklearn.neighbors import KNeighborsClassifier
KNN=KNeighborsClassifier(n_neighbors=5)
KNN.fit(train_x,train_y)

